language:
  node_js
install:
  - npm install
before_script:
  - npm run build
  - npm link
script:
  - npm run coverage
after_success:
  - bash <(curl -s https://codecov.io/bash)
env:
  - NODE_NO_WARNINGS=1
branches:
  only:
    - master
    - development