language:
  node_js
install:
  - npm install
before_script:
  - npm run build
  - npm link
after_success:
  - npm run coverage
env:
  - NODE_NO_WARNINGS=1
branches:
  only:
    - master
    - development